# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Sol de Fierro
tagline:          'Mis reflejos de todos, en español'
description:      'Un blog de mis reflejos sobre todos, en la lengua española'
url:              https://soldefierro.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5
