# Dependencies
highlighter:      redcarpet

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Sol de Fierro
tagline:          'Mis reflejos de todos, en español'
description:      'Un blog de mis reflejos sobre todos, en la lengua española'
url:              https://soldefierro.github.io/
baseurl:          

author:
  name:           'Sol de Fierro'
  url:            https://github.com/soldefierro

paginate:         5
